/**
 * GatewayTigoPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package co.com.tigo.gatewaytigov19.webscp.ws;

public interface GatewayTigoPortType extends java.rmi.Remote {
    public co.com.tigo.gatewaytigov19.webscp.ws.CreditResponseDTO credit(co.com.tigo.gatewaytigov19.webscp.ws.CreditRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.BalanceResponseDTO eBalance(java.lang.String arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.BalanceResponseDTO balance(co.com.tigo.gatewaytigov19.webscp.ws.BalanceRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.EventResponseDTO applicationEvent(co.com.tigo.gatewaytigov19.webscp.ws.EventRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.EventResponseDTO eventAuthorization(co.com.tigo.gatewaytigov19.webscp.ws.EventRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.DebitResponseDTO debit(co.com.tigo.gatewaytigov19.webscp.ws.DebitRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.RechargeResponseDTO recharge(co.com.tigo.gatewaytigov19.webscp.ws.RechargeRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.RechargeRevResponseDTO rechargeReversal(co.com.tigo.gatewaytigov19.webscp.ws.RechargeRevRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ERechargeResponseDTO eRecharge(co.com.tigo.gatewaytigov19.webscp.ws.ERechargeRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ERechargeRevResponseDTO eRechargeReversal(co.com.tigo.gatewaytigov19.webscp.ws.ERechargeRevRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.PromotionDTO[] provideBonus(co.com.tigo.gatewaytigov19.webscp.ws.PromotionDTO[] arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.UserPromotionDTO[] provideUsers(co.com.tigo.gatewaytigov19.webscp.ws.UserPromotionDTO[] arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.PropertyDTO[] provideProperties(co.com.tigo.gatewaytigov19.webscp.ws.PropertyDTO[] arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.PromotionDTO[] consultBonus(co.com.tigo.gatewaytigov19.webscp.ws.PromotionDTO[] arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.UserPromotionDTO[] consultUsers() throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.UserPromotionDTO[] consultEUsersPromotions() throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.PropertyDTO[] consultProperties() throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.TransferResponseDTO transfer(co.com.tigo.gatewaytigov19.webscp.ws.TransferRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.BalanceToResourceResponseDTO balanceToResource(co.com.tigo.gatewaytigov19.webscp.ws.BalanceToResourceRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ETransferResponseDTO eTransfer(co.com.tigo.gatewaytigov19.webscp.ws.ETransferRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.SellerDTO[] provideResources(co.com.tigo.gatewaytigov19.webscp.ws.SellerDTO[] arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.SellerDTO[] consultResources() throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.AdviceOfChargeResponseDTO adviceOfCharge(co.com.tigo.gatewaytigov19.webscp.ws.AdviceOfChargeRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.VoucherRechargeResponseDTO voucherRecharge(co.com.tigo.gatewaytigov19.webscp.ws.VoucherRechargeRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ReservationResponseDTO reservation(co.com.tigo.gatewaytigov19.webscp.ws.ReservationRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ReservationCancelResponseDTO reservationCancel(co.com.tigo.gatewaytigov19.webscp.ws.ReservationCancelRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ReservationModifyResponseDTO reservationModify(co.com.tigo.gatewaytigov19.webscp.ws.ReservationModifyRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ReservationQueryResponseDTO reservationQuery(co.com.tigo.gatewaytigov19.webscp.ws.ReservationQueryRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ReservationUseResponseDTO reservationUse(co.com.tigo.gatewaytigov19.webscp.ws.ReservationUseRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ServiceStateQueryResponseDTO serviceStateQuery(co.com.tigo.gatewaytigov19.webscp.ws.ServiceStateQueryRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ServiceQueryResponseDTO serviceQuery(co.com.tigo.gatewaytigov19.webscp.ws.ServiceQueryRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ServiceChangeResponseDTO serviceChange(co.com.tigo.gatewaytigov19.webscp.ws.ServiceChangeRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ERechargeDealerResponseDTO eRechargeDealer(co.com.tigo.gatewaytigov19.webscp.ws.ERechargeDealerRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ERechargeSellerResponseDTO eRechargeSeller(co.com.tigo.gatewaytigov19.webscp.ws.ERechargeSellerRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ERechargeSellerReversalResponseDTO eRechargeSellerReversal(co.com.tigo.gatewaytigov19.webscp.ws.ERechargeSellerReversalRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ESellProductSellerResponseDTO eSellProductSeller(co.com.tigo.gatewaytigov19.webscp.ws.ESellProductSellerRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
    public co.com.tigo.gatewaytigov19.webscp.ws.ERechargeAdviserResponseDTO eRechargeAdviser(co.com.tigo.gatewaytigov19.webscp.ws.ERechargeAdviserRequestDTO arg0) throws java.rmi.RemoteException, co.com.tigo.gatewaytigov19.webscp.ws.BusinessException, co.com.tigo.gatewaytigov19.webscp.ws.GatewayPrepayWSException;
}
